function out = vp_ext(QpAlpha,QpAlphaPlusOne,x,RCell,vCell,wAlpha)
    % 
    vpext = zeros(size(x));
    Nfrag = length(vCell);
    %
    for i = 1:Nfrag
        vpext = vpext + ... 
                    ( build_vext(x,RCell,vCell,zeros(size(x))) ...
                    - build_vext(x,RCell(i),vCell(i),zeros(size(x))) ) ...
                    *(1 - wAlpha(i)).*(QpAlpha(:,i)) + ...
                    ( build_vext(x,RCell,vCell,zeros(size(x))) ...
                    - build_vext(x,RCell(i),vCell(i),zeros(size(x))) ) ...
                    *wAlpha(i).*(QpAlphaPlusOne(:,i));
    end
    out = vpext;
end